apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fincloud.fullname" . }}-config
  labels:
    {{- include "fincloud.labels" . | nindent 4 }}
data:
  NODE_ENV: production
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  REVISION: {{ .Values.global.revision | quote }}
